ecommerce_app/app/accounts/urls.py
from django.urls import path
from .views import AccountsListView, AccountsUpdateView, LoginView, LogoutView


app_name = 'accounts'

urlpatterns = [
    path('', AccountsListView.as_view(), name='list'),
    path('update', AccountsUpdateView.as_view(), name='update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

ecommerce_app/app/orders/urls.py
from django.urls import path
from .views import OrderDetailView, CloseOrderView, PayOrderiew

app_name = 'orders'

urlpatterns = [
    path('details/<int:pk>', OrderDetailView.as_view(), name='detail'),
    path('close/', CloseOrderView.as_view(), name='close'),
    path('pay/', PayOrderiew.as_view(), name='pay'),
]

ecommerce_app/app/products/urls.py
from django.urls import path
from .views import ProductListView, ProductRetriveView, AddCartView, RemoveFromCartView, CartView, FinalizeCartView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>/', ProductRetriveView.as_view(), name='retrive'),
    path('add', AddCartView.as_view(), name='add'),
    path('remo/<int:id>/', RemoveFromCartView.as_view(), name='remo'),
    path('car', CartView.as_view(), name='car'),
    path('finalize', FinalizeCartView.as_view(), name='finalize')
]

ecommerce_app/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('products/', include('app.products.urls')),
    path('accounts/', include('app.accounts.urls')),
    path('orders/', include('app.orders.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce_app/app/products/models.py
import os 

from PIL import Image

from django.conf import settings
from django.db import models
from app.common import choices
from app import utils
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Produto')   
    descripition = models.TextField(verbose_name='Descrição')
    short_descripition = models.TextField(verbose_name='Descrição Curta', null=True, blank=True)
    image = models.ImageField(upload_to='product_images/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    amount = models.DecimalField(verbose_name='Valor do produto', decimal_places=2, max_digits=8)
    promotional_amount = models.DecimalField(verbose_name='Valor do produto promocional', decimal_places=2, max_digits=8, default=0)
    type = models.CharField(choices=choices.PRODUCT_TYPE, max_length=50, verbose_name='Tipo do produto', default='simple')

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def resize_image(self, img, new_width: int):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_heigth = img_pil.size 

        if original_width  >= new_width:
            new_heigth = (new_width * original_heigth) / original_width
            new_img = img_pil.resize((new_width, new_heigth), Image.LANCZOS)
            new_img.save(
                 img_full_path,
                optimize=True
            )

            print('A imagem foi redimencionada')
        img_pil.close()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

        if self.image:
            self.resize_image(self.image, 800)

    def get_formated_amount(self):
        return utils.format_money(self.amount)
    
    get_formated_amount.short_description = 'Valor'

class Variation(models.Model):
    name = models.CharField(max_length=190, verbose_name='Variação do produto')
    product = models.ForeignKey(Product, verbose_name='ID do Produto', on_delete=models.CASCADE)
    amount = models.DecimalField(verbose_name='Valor do produto', decimal_places=2, max_digits=8)
    promotional_amount = models.DecimalField(verbose_name='Valor do produto promocional', decimal_places=2, max_digits=8, default=0)
    stock = models.IntegerField(verbose_name='Quantidade em estoque', default=1)

    class Meta:
        verbose_name = 'Variação do Produto'
        verbose_name_plural = 'Variações dos produtos'

    def __str__(self) -> str:
        return self.name or self.product.name

ecommerce_app/app/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from .models import Product, Variation
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse
from pprint import pprint

class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'products'
    paginate_by = 1
    
class ProductRetriveView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'

class AddCartView(View):
    def get(self, *args, **kwargs):
        http_refer = self.request.META.get('HTTP_REFERER', reverse('products:list'))
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            messages.error(self.request, 'Produto não existente')
            return redirect(http_refer)
        
        product_variation = get_object_or_404(Variation, pk=variation_id)
        product = product_variation.product

        if product_variation.stock < 1:
            messages.error(self.request, 'EStoque insuficiente')
            return redirect(http_refer)
        
        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()
        
        cart = self.request.session.get('cart')
        if variation_id in cart:
            qtd_product_in_cart = cart[variation_id]['quantity']
            qtd_product_in_cart += 1

            if product_variation.stock < qtd_product_in_cart:
                messages.error(self.request, f"Estoque insuficiente para {qtd_product_in_cart}, no produto {product.name}. Adicionamos {product_variation.stock} no  seu carrinho")
                qtd_product_in_cart = product_variation.stock

            cart[variation_id]['quantity'] = qtd_product_in_cart
            cart[variation_id]['unit_amount'] = float(product.amount * qtd_product_in_cart)
            cart[variation_id]['unit_promotional_amount'] = float(product.promotional_amount * qtd_product_in_cart)

        else:
            cart[variation_id] = {
                'product_id': product.pk,
                'product_name': product.name,
                'variation_name': product_variation.name,
                'variation_id': product_variation.pk,
                'unit_amount': float(product.amount),
                'unit_promotional_amount': float(product.promotional_amount),
                'quantity': 1,
                'slug': product.slug,
                'image': product.image.name or '',
            }

        self.request.session.save()
        messages.success(self.request, f"Produto {product.name} {product_variation.name} adicionado com sucesso ao carrinho.")
        return redirect(http_refer)


class RemoveFromCartView(View):
    def get(self, *args, **kwargs):
        http_refer = self.request.META.get('HTTP_REFERER', reverse('products:list'))
        variation_id = str(kwargs.get('id'))

        if not variation_id or not self.request.session.get('cart') or variation_id not in self.request.session['cart']:
            messages.error(self.request, 'Produto não existente')
            return redirect(http_refer)

        cart = self.request.session.get('cart')
        messages.success(self.request, f"Produto {cart[variation_id].get('product_name')} {cart[variation_id].get('variation_name')} removido do carrinho.")
        

        del cart[variation_id]
        self.request.session.save()
        return redirect(http_refer)

class CartView(View):
    def get(self, *args, **kwargs):
        url_redirect = 'products:finalize' if self.request.user.is_authenticated else 'accounts:list' 
        return render(self.request, 'products/cart.html', context={'btn_url_redirect': url_redirect})

class FinalizeCartView(View):

    
    def get(self, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('accounts:list')
    
        context = {'user': self.request.user, 'cart': self.request.session.get('cart')}
        return render(self.request, 'products/resume.html', context)

ecommerce_app/app/products/templates/products/cart.html
{% extends 'base.html' %}
{% load filters %}
{% load static %}

{% block content %}


    {% if not request.session.cart %}
        Carrinho vazio
    {% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include 'structure/cart.html' %}
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total de itens</td>
                        <td>{{ request.session.cart|calculate_cart_items }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            <a class="btn btn-lg btn-block btn-primary" href="{% url btn_url_redirect %}">
                Finalizar a compra
            </a>
        </div>
    </div>
    {% endif %}
{% endblock content %}

ecommerce_app/app/products/templates/products/detail.html
{% extends 'base.html' %}
{% load filters %}

{% block content %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if product.image %}
                <img class="img-fluid" src="{{ product.image.url }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{ product.name}}</h1>
            <p class="lead">{{ product.short_descripition }}</p>
            <p class="lead">
                {% if product.promotional_amount%}
                <span id="variation-preco" class="lead product-price">{{ product.amount|format_money}}</span>
                <span id="variation-preco-promocional"
                    class="lead product-old-price text-muted">{{ product.promotional_amount|format_money}}</span>
                {% else %}
                    <span id="variation-preco" class="lead product-price">{{ product.amount|format_money}}</span>
                {% endif %}
            </p>

            <form action="{% url 'products:add' %}" id="form-add-to-cart">
                {% if product.type == 'variable' %}
                    <div class="form-group">
                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                            {% for variation in product.variation_set.all %}
                                <option data-preco="{{ variation.amount|format_money }}" data-preco-promocional="{{ variation.amount|format_money }}" value="{{ variation.pk }}">{{variation.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}    
                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>

            </form>


        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ product.descripition}}</h2>
            {{ product.descripition|linebreaks}}
        </div>    
    </div>
</div>
{% endblock content %}

ecommerce_app/app/products/templates/products/list.html
{% extends 'base.html' %}
{% load filters %}

{% block content %} 

    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">
                {% for product in products %}
                    <div class="card">
                        {% if product.image %}
                            <a href="{{ product.slug }}">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name}}">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.short_descripition }}</p>
                            <div class="container product-price-block text-center">
                                {% if product.promotional_amount %}
                                    <span class="product-price">
                                        {{ product.promotional_amount|format_money}}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ product.amount|format_money }}
                                    </span>
                                {% else %}
                                    <span class="product-price">
                                        {{ product.promotional_amount|format_money}}
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{{ product.slug }}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div> 
                {% endfor %}   
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='col-lg-12'>
            {% include 'structure/pagination.html' %}
        </div>
    </div>     
{% endblock content %}

ecommerce_app/app/products/templates/products/resume.html
{% extends 'base.html' %}

{% block content %}


    <div class="row mb-5">
        <div class="col-lg">
            <h2>Resumo da sua compra</h2>

            <p class="lead">Dados do usuário</p>
            <p>Caso precise editar, <a href="{% url 'accounts:update' %}">clique aqui</a></p>
            <dl class="row">
                <dt class="col-lg-2">Nome:</dt>
                <dd class="col-lg-4">{{user.name}}</dd>
                <dt class="col-lg-2">{{user.first_name}}</dt>
                <dd class="col-lg-4">{{user.last_name}}</dd>

                <dt class="col-lg-2">Idade:</dt>
                <dd class="col-lg-4">{{user.profile_age}}</dd>
                <dt class="col-lg-2">Nascimento:</dt>
                <dd class="col-lg-4">{{user.profle_birth_date}}</dd>

                <dt class="col-lg-2">CPF:</dt>
                <dd class="col-lg-4">{{user.profile.document}}</dd>
                <dt class="col-lg-2">E-mail:</dt>
                <dd class="col-lg-4">{{user.email}}</dd>
            </dl>

            <p class="lead">Dados de endereço</p>
            <p>Caso precise editar, <a href="{% url 'accounts:update' %}">clique aqui</a></p>
            <dl class="row">
                <dt class="col-lg-2">Endereço:</dt>
                <dd class="col-lg-4">Av. Filho Junior</dd>
                <dt class="col-lg-2">Número:</dt>
                <dd class="col-lg-4">12</dd>

                <dt class="col-lg-2">Complemento:</dt>
                <dd class="col-lg-4">Casa</dd>
                <dt class="col-lg-2">Nascimento:</dt>
                <dd class="col-lg-4">Centro</dd>

                <dt class="col-lg-2">Cidade:</dt>
                <dd class="col-lg-4">São Paulo</dd>
                <dt class="col-lg-2">Estado:</dt>
                <dd class="col-lg-4">SP</dd>

                <dt class="col-lg-2">CEP:</dt>
                <dd class="col-lg-4">00000000</dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'structure/cart.html' %}
            <a class="btn btn-block btn-primary btn-lg" href="{% url 'orders:pay' %}">
                Realizar pedido e pagar
            </a>
        </div>
    </div>


{% endblock content %}