ecommerce_app/app/products/urls.py
from django.urls import path
from .views import ProductListView, ProductRetriveView, AddCartView, RemoveFromCartView, CartView, FinalizeCartView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>/', ProductRetriveView.as_view(), name='retrive'),
    path('add', AddCartView.as_view(), name='add'),
    path('remo/<int:id>/', RemoveFromCartView.as_view(), name='remo'),
    path('car', CartView.as_view(), name='car'),
    path('finalize', FinalizeCartView.as_view(), name='finalize')
]

ecommerce_app/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('products/', include('app.products.urls')),
    path('accounts/', include('app.accounts.urls')),
    path('orders/', include('app.orders.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce_app/templates/structure/cart.html
{% load static %}
{% load filters %}


<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>
        {% for product_cart in request.session.cart.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %} {{ product_cart.image }}">
            </td>
            <td>
                <a href="{% url 'products:retrive' product_cart.slug %}">
                    {{ product_cart.product_name }}
                    <a class="ml-3" href="{% url 'products:remo' product_cart.variation_id %}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </a>
            </td>
            <td>{{ product_cart.variation_name }}</td>
            <td>{{ product_cart.quantity }}</td>
            {% if product_cart.unit_promotional_amount %}
            <td>{{ product_cart.unit_promotional_amount|format_money }}</td>
            {% else %}
            <td>{{ product_cart.unit_amount|format_money }}</td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
</div>

ecommerce_app/templates/structure/footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Guilherme Costa</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

ecommerce_app/templates/structure/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

ecommerce_app/templates/structure/messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

ecommerce_app/templates/structure/nav.html
{% load filters %}
    
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'products:list' %}">Ecommerce App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'products:list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            {% if request.session.cart %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'products:car' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{request.session.cart|calculate_cart_items}}</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

ecommerce_app/templates/structure/pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
        {% endif %}
    </ul>
</div>
{% endif %}